# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_each_boot1 <- function(formula, data, n) {
    .Call('_blblm_lm_each_boot1', PACKAGE = 'blblm', formula, data, n)
}

