# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' lm_each_boot
#' @param how many parts that we want to split
#' @param formula an object of class "formula" (or one that can be coerced to that class): a symbolic description of the model to be fitted.
#' @param data an optional data frame, list or environment (or object coercible by as.data.frame to a data frame) containing the variables in the model.
#' @param n number of multiprobability
#' @export
#'
lm_each_boot1 <- function(formula, data, n) {
    .Call('_blblm_lm_each_boot1', PACKAGE = 'blblm', formula, data, n)
}

